# Generated by Django 4.0.6 on 2022-07-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colours',
            new_name='Colour',
        ),
        migrations.RenameModel(
            old_name='Handles',
            new_name='Handle',
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
    ]
