# Generated by Django 4.0.6 on 2022-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_colours_colour_rename_handles_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(max_length=500)),
                ('main_photo', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(max_length=500)),
                ('main_photo', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='facades',
            field=models.ManyToManyField(to='shop.facade'),
        ),
        migrations.AddField(
            model_name='product',
            name='slabs',
            field=models.ManyToManyField(to='shop.slab'),
        ),
    ]
